#spring:
#  datasource:
#    generate-unique-name: false
#    name: testdb
#  h2:
#    console:
#      enabled: true
#      path: /h2-console/
#
spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/data_generator
    username: postgres
    password: Simform@123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      show-sql: false
      ddl-auto: update
    properties:
      hibernate:
        default_schema: company
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8083