CREATE SCHEMA IF NOT EXISTS book;
CREATE SCHEMA IF NOT EXISTS business
CREATE SCHEMA IF NOT EXISTS color;
CREATE SCHEMA IF NOT EXISTS company;
CREATE SCHEMA IF NOT EXISTS commerce;
CREATE SCHEMA IF NOT EXISTS country;
CREATE SCHEMA IF NOT EXISTS currency;
CREATE SCHEMA IF NOT EXISTS demographic;
CREATE SCHEMA IF NOT EXISTS educator;
CREATE SCHEMA IF NOT EXISTS file;
CREATE SCHEMA IF NOT EXISTS food;
CREATE SCHEMA IF NOT EXISTS hacker;
CREATE SCHEMA IF NOT EXISTS internet;
CREATE SCHEMA IF NOT EXISTS job;
CREATE SCHEMA IF NOT EXISTS lorem;
CREATE SCHEMA IF NOT EXISTS medical;
CREATE SCHEMA IF NOT EXISTS nation;
CREATE SCHEMA IF NOT EXISTS programming_language;
CREATE SCHEMA IF NOT EXISTS relationship;
CREATE SCHEMA IF NOT EXISTS weather;
CREATE SCHEMA IF NOT EXISTS name;







